### PR TITLE
updates to rust deps

### PR DESCRIPTION
**Pull request by chanelmoreno**
This change is [Reviewable](https://reviewable.io/reviews/WORK180/auth0-management/8)

### CODE REVIEW

**Comment by kingsleyh** [comment]
What is the status of this project - I got here via a PR on the original repo (which seems dead) but then I saw on this fork there is this PR.

**Review by mterring — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/WORK180/auth0-management/8)* status: all files reviewed, 1 unresolved discussion (waiting on @chanelmoreno)

___
*[`src/lib.rs` line 69 at r1](https://reviewable.io/reviews/WORK180/auth0-management/8#-Nv59S2bEOPKqhTCSB3f:-Nv59S2c3Z1FqGURkVLW:bbdf5df) ([raw file](https://github.com/WORK180/auth0-management/blob/2132e80efef9c0bc5387ca6161f67416a8de6437/src/lib.rs#L69)):*
> ```XML
> pub use api::*;
> pub use builder::*;
> pub use client::*;
> ```

Why was this removed?

**Comment by chanelmoreno** [comment]
*[`src/lib.rs` line 69 at r1](https://reviewable.io/reviews/WORK180/auth0-management/8#-Nv59S2bEOPKqhTCSB3f:-Nv5KXiQ2aZSx214UTBs:bjt4gle) ([raw file](https://github.com/WORK180/auth0-management/blob/2132e80efef9c0bc5387ca6161f67416a8de6437/src/lib.rs#L69)):*
<details><summary><i>Previously, mterring (Michael Terrington) wrote…</i></summary><blockquote>

Why was this removed?
</blockquote></details>

It was giving an unused client warning, so cleaned it up by removing it.

**Comment by chanelmoreno** [comment]
*[`src/lib.rs` line 69 at r1](https://reviewable.io/reviews/WORK180/auth0-management/8#-Nv59S2bEOPKqhTCSB3f:-Nv5Kw6u16dNVxK3snib:boldg5v) ([raw file](https://github.com/WORK180/auth0-management/blob/2132e80efef9c0bc5387ca6161f67416a8de6437/src/lib.rs#L69)):*
<details><summary><i>Previously, chanelmoreno (Chanel Moreno) wrote…</i></summary><blockquote>

It was giving an unused client warning, so cleaned it up by removing it.
</blockquote></details>

an an unused warning*

**Review by mterring — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/WORK180/auth0-management/8)* status: all files reviewed, 1 unresolved discussion (waiting on @chanelmoreno)

___
*[`src/lib.rs` line 69 at r1](https://reviewable.io/reviews/WORK180/auth0-management/8#-Nv59S2bEOPKqhTCSB3f:-Nv5P5rVEsAw8RN7b2bj:bc8bg35) ([raw file](https://github.com/WORK180/auth0-management/blob/2132e80efef9c0bc5387ca6161f67416a8de6437/src/lib.rs#L69)):*
<details><summary><i>Previously, chanelmoreno (Chanel Moreno) wrote…</i></summary><blockquote>

an an unused warning*
</blockquote></details>

That's really weird - it's a library, you can't tell who might use it! Pretty sure it should stay

**Review by chanelmoreno — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/WORK180/auth0-management/8)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @mterring)

___
*[`src/lib.rs` line 69 at r1](https://reviewable.io/reviews/WORK180/auth0-management/8#-Nv59S2bEOPKqhTCSB3f:-Nv5PdKv-xpy7NfPKko7:b-u95s1l) ([raw file](https://github.com/WORK180/auth0-management/blob/2132e80efef9c0bc5387ca6161f67416a8de6437/src/lib.rs#L69)):*
<details><summary><i>Previously, mterring (Michael Terrington) wrote…</i></summary><blockquote>

That's really weird - it's a library, you can't tell who might use it! Pretty sure it should stay
</blockquote></details>

Ahhh ok understood. Trusted intellisense a little too much.

**Review by mterring — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/WORK180/auth0-management/8)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @chanelmoreno)

**Pull request merged**
